[package]
name = "mydecaf"
version = "0.1.0"
authors = ["Yang Dong <yangdong020111@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parser-macros = { git = "https://github.com/MashPlant/lalr1" }
